Repository Juarpla/wdd330, pull requests merged in 2024-05, with the labels that each got.

#3 W01 Individual Activity: Add Item to Cart Broken, completed.
  src/index.html
  src/js/utils.mjs
  src/json/tents.json
  team.txt
Labels: bug

#6 Attempted fix at empty card issue in cart.html
  src/js/cart.js
Labels: enhancement

#9 Finished the card getting total of the items in the cart.
  src/cart/index.html
  src/js/cart.js
Labels: enhancement

#15 Fixed the listing price and quantity.
  src/js/utils.mjs
Labels: bug

#16 Remove hard coded products in home page
  src/index.html
Labels: bug

#20 Animate cart (backpack) icon when item added to cart.
  src/css/style.css
  src/js/ProductDetails.mjs
  src/js/animations.js
Labels: enhancement

#22 Add remove item from cart button
  src/css/style.css
  src/js/ShoppingCart.mjs
Labels: enhancement

#19 Add customizable alert to index
  src/css/style.css
  src/index.html
  src/js/Alert.js
  src/js/product-listing.js
  src/js/product.js
  src/product-listing/index.html
  src/public/json/alerts.json
  vite.config.js
Labels: enhancement

#24 Jr individual3.1
  src/css/style.css
  src/index.html
  src/js/Alert.js
  src/js/ProductData.mjs
  src/js/ProductDetails.mjs
  src/js/ProductList.mjs
  src/js/ShoppingCart.mjs
  src/js/main.js
  src/js/product-listing.js
  src/js/product.js
  src/product-listing/index.html
  src/product_pages/index.html
  src/public/json/alerts.json
Labels: bug, enhancement

#25 Fix product links
  src/js/ProductList.mjs
  src/js/ShoppingCart.mjs
Labels: bug

#27 Product list sort
  src/css/style.css
  src/js/ProductList.mjs
  src/product-listing/index.html
Labels: enhancement

#33 Add missing link on vite config
  vite.config.js
Labels: bug

#35 Add buttons to change quantities in cart page
  src/css/style.css
  src/js/ShoppingCart.mjs
Labels: enhancement

#36 Add discount indicators
  src/css/style.css
  src/js/ProductDetails.mjs
  src/js/ProductList.mjs
  src/js/utils.mjs
Labels: enhancement
